#!/usr/bin/env node

var x = 0;
var max = Number(process.argv[2]);

if (isNaN(max)) {
  max = 50;
}

function timeoutCallback() {
  console.log('some output for iteration', x);
  x++;

  if (max === 0 || x < max) {
    if (Math.random() < 0.05) {
      setTimeout(timeoutCallback, 500 + (Math.random() * 500));
    }
    else {
      setTimeout(timeoutCallback, 0);
    }
  }
}

setTimeout(timeoutCallback, 1);
