#!/usr/bin/env node

var x = 0;

function timeoutCallback() {
  console.log('some output for iteration', x);
  x++;

  if (x < 50) {
    if (Math.random() < 0.15) {
      setTimeout(timeoutCallback, 500 + (Math.random() * 500));
    }
    else {
      setTimeout(timeoutCallback, Math.random() * 100);
    }
  }
}

setTimeout(timeoutCallback, 1);
